---
title: "Bivariate Moran Index"
subtitle: "Análisis espacial"
author: "Diana Villasana Ocampo"
knit: (function(inputFile, encoding) {
       rmarkdown::render(inputFile, encoding = encoding, output_dir = "../Output/")
  })
output:
   html_document:
      code_folding: hide
      highlight: tango
      theme: flatly
      toc: true
      toc_depth: 3
      toc_float:
        collapsed: yes
---

```{=html}
<style type="text/css">
body {
text-align: justify;
font-style: normal;
font-family: "Montserrat";
font-size: 12px
}
h1.title {
  font-size: 40px;
  color: #000D3B;
}
h1 {
  color: #B6854D;
}
h2 {
  color: #172984;
}
h3 {
  color: #172984;
}
</style>
```

```{=html}
<style>
.nav>li>a {
    position: relative;
    display: block;
    padding: 10px 15px;
    color: #1C3BA4
}
.nav-pills>li.active>a, .nav-pills>li.active>a:hover, .nav-pills>li>a:focus {
    color: #ffffff;
    background-color: #09C2BC
}
</style>
```

```{=html}
<style>
.tile1-text {
    position: relative;
    display: block;
    padding: 10px 15px;
    color: #0A6A87;
    list-style: none;
}
.top1-tiles a:nth-of-type(1):hover, .top-tiles1 a:nth-of-type(1):focus{
    color: #ffffff;
    background: #0A6A87
}
</style>
```

```{=html}
<style>
.tile2-text {
    position: relative;
    display: block;
    padding: 10px 15px;
    color: #0A6CC8;
    list-style: none;
}
.top2-tiles a:nth-of-type(1):hover, .top2-tiles a:nth-of-type(1):focus{
    color: #ffffff;
    background: #0A6CC8
}
</style>
```

```{=html}
<style>
.math {
  font-size: 15px;
  color: #1e42ab;
}
</style>
```

## Objetivo 

## Análisis espacial  

## Correlaciones espaciales

### 1. Moran's I Bivariado (Bivariate Moran's I) 
 
  Este método mide la correlación espacial entre dos variables en diferentes ubicaciones. Se calcula como:  
  \[
    I_B = \frac{\sum_i \sum_j w_{ij} (X_i - \bar{X}) (Y_j - \bar{Y})}{S^2 \sum_i \sum_j w_{ij}}
    \]  

donde:  

- \( X_i \) es la variable de pobreza en la unidad espacial \( i \).  
- \( Y_j \) es la variable de equipamiento en la unidad espacial \( j \).  
- \( w_{ij} \) es la matriz de pesos espaciales.  
- \( S^2 \) es la varianza de \( X \).  

 
### 2. LISA Bivariado (`Bivariate Local Moran’s I`)     

Permite identificar agrupaciones espaciales locales entre dos variables. Se puede calcular con `spdep::localmoran()`, utilizando una variable como \( X \) y la otra como \( Y \).  

### 3. Getis-Ord Bivariado (Bivariate G)
Este método identifica zonas de altas y bajas correlaciones espaciales entre dos variables.

### 4. Geary's C Bivariado
Detecta autocorrelación espacial, pero con más sensibilidad a diferencias locales.


